delayed publisher
veoo/rabbit-smpp pull request #4
Opened 2016-10-03 11:40 UTC by makkalot

2016-10-03 11:49 UTC, cesarrodrig requested changes

2016-10-03 11:49 UTC, cesar0094 commented on rabbitsmpp/publisher.go
> +	if err != nil {
Repeated from the other PR. `return ch.Publish(...` is shorter :)

2016-10-03 12:13 UTC, makkalot commented on rabbitsmpp/publisher.go
> +	if err != nil {
👍

2016-10-05 09:02 UTC, makkalot commented on rabbitsmpp/publisher.go
> +	if err != nil {
Done in #f7f0e91

2016-10-05 13:18 UTC, cesarrodrig approved these changes

2016-10-31 11:41 UTC, merged